### ISSUE TITLE
hover_with_actions is deprecated

### ISSUE THREAD

**Issue by ctuffli** [sharksforarms/sharksforarms.github.io#19] opened 2022-10-14 23:53 UTC
When using the example configuration with neovim v0.8.0 and the latest rust-tools.nvim, neovim displays the error:

`rust-tools: hover_with_actions is deprecated, please setup a keybind to :RustHoverActions in on_attach instead`

**Comment by sharksforarms** [comment] 2022-10-22 23:00
Cannot reproduce this with the [latest config](https://github.com/sharksforarms/neovim-rust/blob/master/neovim-init-lsp-cmp-rust-tools.lua). Closing for now.

**Closed as completed by sharksforarms** 2022-10-22 23:00 UTC
